### ISSUE TITLE
wrong info about npm version ?

### ISSUE THREAD

**Issue by Seqway** [ldittmar81/ioBroker.info#12]
Hello,
i updated my Testsystem completly and run now node 10.15 und npm 6.7 but info Adapter shows me still version 6.4.1 - see attached files:

<img width="170" alt="bildschirmfoto 2019-01-28 um 12 31 35" src="https://user-images.githubusercontent.com/40624961/51833868-f807b800-22f8-11e9-84aa-e087994d7011.png">
<img width="475" alt="bildschirmfoto 2019-01-28 um 12 30 54" src="https://user-images.githubusercontent.com/40624961/51833869-f8a04e80-22f8-11e9-919a-907cc96496f0.png">

**Comment by ldittmar81** [comment]
Hi,

die Daten kommen vom js-controller. Ich habe da kein Einfluss darauf. Hmm... Hat es sich inzwischen von selbst gelöst? Vielleicht wird der Wert gecached? In der Übersichtsseite stehen die Daten auch. Wenn es dort auch falsch sein sollte, dann ist das wirklich ein Fehler im js-controller.
