### ISSUE TITLE
IOBroker Forum und News ist leer

### ISSUE THREAD

**Issue by Hypnos3** [ldittmar81/ioBroker.info#2]
In den Einstellungen aktiviert:
![image](https://user-images.githubusercontent.com/12692680/35556716-520893d4-05a3-11e8-823a-ea1327e5df30.png)

Aber kein Inhalt:
![image](https://user-images.githubusercontent.com/12692680/35556730-59a50500-05a3-11e8-978a-9fb4cbf86840.png)

Der Feed enthält hingegen EInträge:
![image](https://user-images.githubusercontent.com/12692680/35556756-69e776aa-05a3-11e8-882c-4052f524a41a.png)

**Comment by robdg80** [comment]
Liegt vermutlich an der FIrewall hier.

**Comment by sigi2345** [comment]
Hallo, der selbe Fehler kommt wieder.

[https://forum.iobroker.net/viewtopic.php?f=36&p=224782#p224760](url)

**Comment by Ilovegym66** [comment]
Push this issue.. ;-) new forum is online, time to take a look for a update?
:-)

**Comment by ldittmar81** [comment]
Yes... I know. I just need some time. Maybe I can do it this week.
