### ISSUE TITLE
Keine Anzeigen von ioBroker News

### ISSUE THREAD

**Issue by UweRP** [ldittmar81/ioBroker.info#3]
Hallo.

Bei mir zeigt der Adapter keine News an. So wie ich es aktuell mitbekommen habe sollte dies aber der Fall sein.
![info](https://user-images.githubusercontent.com/17329042/38714835-58c245f8-3ed8-11e8-8fe0-2ace8bfbb791.jpg)
![info einstellung](https://user-images.githubusercontent.com/17329042/38714843-60fb31ee-3ed8-11e8-97d1-24bf3e17174a.jpg)

**Comment by smaragdschlange** [comment]
Hi,
bei mir ist es das gleiche Bild...weder News noch Forum :(

**Comment by Ilovegym66** [comment]
bei mir gehts, es funktioniert aber nicht, wenn der admin-adapter auf https steht...schaltet mal die Authentifizierung ab, dann gehts bestimmt.

**Comment by smaragdschlange** [comment]
Zumindest bei mir kann das nicht das Problem sein. HTTPS und Authentifizierung sind bei mir im Admin Adapter ausgeschaltet.

**Comment by Ilovegym66** [comment]
Hmm hier nur mit https nachvollziehbar, NPM 6.4.1, Node 8.12, js-controller 1.4.2, iobroker.admin 3.5.10, iobroker.web 2.4.2
Was könnte noch Einfluss haben?

**Comment by smaragdschlange** [comment]
NPM 3.10.10 Node v6.14.3 js-controller 1.4.2 iobroker.admin 3.5.10 iobroker.web 2.4.1 (wird bei mir als neueste Version angezeigt, obwohl ich das Latest-Repository benutze).
Hmm, Node Version 6 ist immernoch die empfohlene... vielleicht sollte ich npm updaten.

**Comment by Ilovegym66** [comment]
ja, es wird entweder NPM 4.6.1 oder höher 5.7.1 empfohlen, ich habe mit Node8.x und NPM 6.x keine Probleme.. 
Der iobroker.web hab ich von Git gezogen, da liegt 2.4.2

**Comment by smaragdschlange** [comment]
Hm, ich hab jetzt NPM, Node, Nodejs und den Web-Adapter aktualisiert:
NPM 6.4.1, Node 8.12.0, Nodejs 8.12.0. js-controller 1.4.2, iobroker.admin 3.5.10, iobroker.web 2.4.2
danach hab ich ./reinstall.sh ausgeführt und mein Tinkerboard rebootet.
Leider hat sich auf dem Info-Tab gar nichts verändert :(
Naja, immerhin hab ich jetzt ein aktualisiertes System ;)

**Comment by ldittmar81** [comment]
Es könnte jetzt mit Version 1.0.1 funktionieren. Bitte testen.
