### ISSUE TITLE
Version 1.0.x no german forum any more..

### ISSUE THREAD

**Issue by Ilovegym66** [ldittmar81/ioBroker.info#7]
since version 1.0.x there are no german forum news any more, and Date at 13.11.2018 ( today 1.12.18!) :-)

![screenshot_2018-12-01 info - iobroker](https://user-images.githubusercontent.com/36229898/49328621-1c9f1800-f574-11e8-955c-6649c77e3d27.png)

**Comment by ldittmar81** [comment]
Hello... it is not only since version 1.0.x - ist because of the new version of the forum phbBB. I will fix it with the next version. Thanks.

**Comment by ldittmar81** [comment]
It's because you can only read threads when you're logged in. However, Russian threads can also be read if you are not logged in. It was done to eliminate the load on the server through bots.
